
clean:
	rm -f *.deh *.dex *.o *.elf *.self *.481 *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

all:
	rm -f *. deh *.o *.elf *.self *.481 *.bin *.481e *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_481e --no-print-directory
	rm -f *.o *.elf *.self ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o


