
clean:
	rm -f *.o *.elf *.bin ../lv1/src/*.o

all:
	rm -f *.o *.elf *.bin ../lv1/src/*.o
	make -f Makefile_470C --no-print-directory

	rm -f *.o *.elf ../lv1/src/*.o
	make -f Makefile_470D --no-print-directory

