
clean:
	rm -f *.o *.elf *.bin ../lv1/src/*.o

all:
	rm -f *.o *.elf *.bin ../lv1/src/*.o
	make -f Makefile_475C --no-print-directory

	rm -f *.o *.elf ../lv1/src/*.o
	make -f Makefile_475D --no-print-directory

