

clean:

	rm -f *.o *.elf *.self *self_DEBUG *.481 *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o



all:

	rm -f *.o *.elf *.self *.self_DEBUG *.481 *.bin *.481E *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

	make -f Makefile_481E --no-print-directory



	rm -f *.o *.elf *.self_DEBUG *.481 *.bin *.481E *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

	make -f Makefile_481E_DEBUG --no-print-directory



	rm -f *.o *.elf  *.481 *.bin *.481E *.481d *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o



dbg:

	rm -f *.o *.elf *.self_DEBUG *.self *.481 *.bin *.481E *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

	make -f Makefile_481E_DEBUG --no-print-directory



	rm -f *.o *.elf  *.481 *.bin *.481E *.481d *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o



re:

	rm -f *.o *.elf *.self_DEBUG *.self *.481 *.bin *.481E *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

	make -f Makefile_481E --no-print-directory



	rm -f *.o *.elf  *.481 *.bin *.481E *.481d *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
