
clean:
	rm -f *.cex *.dex *.o *.elf *.self *.481 *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

all:
	rm -f *. cex *.o *.elf *.self *.481 *.bin *.481c *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_481C --no-print-directory

	rm -f *.dex *.o *.elf *.481 *.481d *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_481D --no-print-directory
	rm -f *.o *.elf *.self ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o


